language: go

# S: Build Lifecycle
install:
  - go get github.com/InkProject/ink
  # - ink build $GOPATH/src/github.com/InkProject/ink/template
  - ink build
# before_script

script:
  - cd ./docs
  - git init
  - git config user.name "godslovecats"
  - git config user.email "marifry@yandex.ru"
  - git add .
  - git commit -m "update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

# after-script:
# E: Build Lifecycle

branches:
  only:
    - master
env:
  global:
    - GH_REF: github.com/godslovecats/blogtest
    - GH_TOKEN: cd032ca5a146f4d0b5d4d95d96ec7d52b09d674d