site:
    title: "blog"
    subtitle: "blog"
    limit: 10
    theme: theme
    lang: ru
    url: "https://github.com/godslovecats/blogtest"
    comment: blog
    logo: "-/images/avatar.png"
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    root: "/blogtest"

build:
    output: "docs"
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
        - "README.md"
    # Excuted command when use 'ink publish'
    publish: |
        git add .
        git commit -m "update"
        git push origin master