site:
    title: "blog"
    subtitle: "blog"
    limit: 10
    theme: theme
    lang: ru
    url: "https://github.com/godslovecats/blogtest"
    comment: blog
    logo: "-/images/avatar.png"
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    # root: "/blogtest"

build:
    output: "docs"
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
        - "README.md"
    # Excuted command when use 'ink publish'
    publish: |
        git add .
        git commit -m "update"
        git push --force --quiet "https://cd032ca5a146f4d0b5d4d95d96ec7d52b09d674d@github.com/godslovecats/blogtest/" origin master