site:
    title: "Decembrist blog"
    subtitle: "blog"
    limit: 10
    theme: theme
    lang: ru
    url: "https://godslovecats.github.io/blogtest/"
    comment: godslovecats
    logo: "-/images/avatar.png"
    link: "/{title}.html"
    root: "/blog"

authors:
    me:
        name: "name"
        intro: "intro"
        avatar: "-/images/avatar.png"

build:
    # output: "public"
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "update"
        git push origin
